---
title: "Sudan CMAM Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    social: menu
    source_code: https://github.com/katilingban/sudanCMAM
    theme: cerulean
---

```{r setup, include = FALSE}
if(!require(flexdashboard)) install.packages("flexdashboard")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(magrittr)) install.packages("magrittr")
if(!require(plotly)) install.packages("plotly")
if(!require(vistime)) install.packages("vistime")
if(!require(lubridate)) install.packages("lubridate")
if(!require(leaflet)) install.packages("leaflet")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(remotes)) install.packages("remotes")
if(!require(squeacr)) remotes::install_github("rapidsurveys/squeacr")
if(!require(sudan)) remotes::install_github("spatialworks/sudan")

library(flexdashboard)
library(ggplot2)
library(magrittr)
library(plotly)
library(vistime)
library(lubridate)
library(leaflet)
library(RColorBrewer)
library(remotes)
library(squeacr)
library(sudan)

## Create Mapbox base layer objects for leaflet mapping
mapbox.satellite <- "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.street    <- "https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.dark      <- "https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.light     <- "https://api.mapbox.com/styles/v1/mapbox/light-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.moonlight <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj3nban30001z2rpahc10c9ef/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.northstar <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj4ke832y4sng2spe2ds4fs55/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.standard  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5di36jn0gxg2rphjn3yetpt/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.decimal   <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5ms1akt3pbi2smtcewsex9m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.terminal  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj6g0tzbd30kc2sph2wyh666m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"

## Load UNICEF palette
unicef_blue      <- "#1CABE2"
unicef_darkgreen <- "#00833D"
unicef_green     <- "#80BD41"
unicef_yellow    <- "#FFC20E"
unicef_orange    <- "#F26A21"
unicef_red       <- "#E2231A"
unicef_darkred   <- "#961A49" 
unicef_purple    <- "#6A1E74"
unicef_warmgrey  <- "#D8D1C9"
unicef_coolgrey  <- "#777779"
unicef_black     <- "#2D2926"
unicef_darkblue  <- "#374EA2"

## UNICEF ggplot theme settings
unicef_theme <- theme_bw() +
  theme(plot.title = element_text(size = 16, colour = unicef_darkblue),
        plot.subtitle = element_text(size = 14, colour = unicef_blue),
        panel.border = element_rect(colour = unicef_darkblue,
                                    size = 0.5),
        panel.grid.major = element_line(linetype = 0),
        panel.grid.minor = element_line(linetype = 0),
        strip.background = element_rect(colour = unicef_darkblue,
                                        fill = unicef_darkblue),
        strip.text = element_text(colour = "white", size = 12),
        legend.key = element_rect(linetype = 0),
        legend.key.size = unit(x = 12, units = "points"),
        legend.spacing = unit(x = 4, units = "points"),
        legend.text = element_text(size =  12),
        axis.line.x = element_line(colour = unicef_darkblue, size = 0.5),
        axis.text.x = element_text(size = 10, colour = unicef_darkblue),
        axis.title.x = element_text(size = 12, colour = unicef_blue),
        axis.text.y = element_text(size = 10, colour = unicef_darkblue),
        axis.title.y = element_text(size = 12, colour = unicef_blue),
        axis.ticks = element_line(colour = unicef_darkblue, size = 0.25))

## Katilingban theme
katilingban_theme <- theme_bw() +
  theme(panel.border = element_rect(colour = "gray50",
                                    size = 0.5),
        panel.grid.major = element_line(linetype = 1,
                                        size = 0.1,
                                        colour = "gray90"),
        panel.grid.minor = element_line(linetype = 0),
        strip.background = element_rect(colour = "gray50",
                                        fill = "gray70"),
        strip.text = element_text(colour = "white", size = 12),
        legend.text = element_text(size = 12),
        legend.key = element_rect(linetype = 0),
        legend.key.size = unit(0.5, "cm"),
        legend.position = "top",
        axis.title = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.ticks = element_line(colour = "gray50", size = 0.5))

legend.format <- function (prefix = "", 
                           suffix = "", 
                           between = " &ndash; ", 
                           digits = 3, 
                           big.mark = ",", 
                           transform = identity) {
  formatNum <- function(x) {
    format(round(transform(x), digits), trim = TRUE, 
           scientific = FALSE, big.mark = big.mark)
  }
    function(type, ...) {
        switch(type, numeric = (function(cuts) {
            paste0(prefix, formatNum(cuts), suffix)
        })(...), bin = (function(cuts) {
            n = length(cuts)
            paste0(prefix, formatNum(cuts[-n]), between, formatNum(cuts[-1]), 
                suffix)
        })(...), quantile = (function(cuts, p) {
            n = length(cuts)
            p = paste0(round(p * 100), "%")
            cuts = paste0(formatNum(cuts[-n]), between, formatNum(cuts[-1]), suffix)
        })(...), factor = (function(cuts) {
            paste0(prefix, as.character(transform(cuts)), suffix)
        })(...))
    }
}
```

Sidebar {.sidebar}
================================================================================

```{r}
selectInput(inputId = "chosen_month",
            label = "Select month",
            choices = unique(monitoring$Month),
            selected = NULL)

selectInput(inputId = "chosen_year",
            label = "Select year",
            choices = unique(monitoring$Year),
            selected = NULL)

selectInput(inputId = "state_name",
            label = "Select state",
            choices = unique(monitoring$State),
            selected = NULL)
```

#### Performance indicators

```{r}
checkboxInput(inputId = "standards",
              label = "Show Sphere standards",
              value = FALSE)
```

#### Responsiveness settings

```{r}
checkboxInput(inputId = "smooth",
              label = "Smooth the curve",
              value = FALSE)
```

Performance
================================================================================

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### National

```{r, fig.height = 6}
x <- reactive({
  aggregate(cbind(Cured, Death, Default, `Non-Responder`) ~ Month + Year, 
            data = monitoring, FUN = sum) %>% 
    calculate_performance() %>%
    filter(Year == input$chosen_year) %>%
    mutate(`Cure Rate` = cured_prop * 100,
           `Defaulter Rate` = defaulter_prop * 100,
           `Death Rate` = dead_prop * 100,
           `Non-response Rate` = nr_prop * 100,
           Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))
})

output$performance <- renderPlotly({
  z <- x() %>% 
    ggplot(mapping = aes(x = Month, group = Year)) +
    geom_line(mapping = aes(y = `Cure Rate`), colour = "darkgreen") +
    geom_line(mapping = aes(y = `Death Rate`), colour = "black") +
    geom_line(mapping = aes(y = `Defaulter Rate`), colour = "red") +
    geom_line(mapping = aes(y = `Non-response Rate`), colour = "gray70") +
    scale_y_continuous(limits = c(0, 100),
                                  breaks = seq(from = 0, to = 100, by = 10)) +
    labs(title = input$chosen_year, y = "%")
  
  sphere_cure <- geom_hline(yintercept = 75, 
                            colour = "darkgreen", 
                            linetype = 2, size = 0.25)
  
  sphere_default <- geom_hline(yintercept = 15, 
                               colour = "red", 
                               linetype = 2, size = 0.25)
    
  sphere_dead <- geom_hline(yintercept = 10, 
                            colour = "black", 
                            linetype = 2, size = 0.25)
  
  ## Assemble plot
  if(input$standards) {
    z <- z + sphere_cure + sphere_default + sphere_dead + unicef_theme
  } else {
    z <- z + unicef_theme
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "performance")
```

### State

```{r}
xstate <- reactive({
  aggregate(cbind(Cured, Death, Default, `Non-Responder`) ~ State + Month + Year, 
               data = monitoring, FUN = sum) %>% 
    calculate_performance() %>%
    filter(Year == input$chosen_year) %>%
    mutate(`Cure Rate` = cured_prop * 100,
           `Defaulter Rate` = defaulter_prop * 100,
           `Death Rate` = dead_prop * 100,
           `Non-response Rate` = nr_prop * 100,
           Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))
})

output$state_performance <- renderPlotly({
  z <- xstate() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = `Cure Rate`), colour = "darkgreen") +
    geom_line(mapping = aes(y = `Death Rate`), colour = "black") +
    geom_line(mapping = aes(y = `Defaulter Rate`), colour = "red") +
    geom_line(mapping = aes(y = `Non-response Rate`), colour = "gray70") +
    scale_y_continuous(limits = c(0, 100),
                       breaks = seq(from = 0, to = 100, by = 10)) +
    labs(title = input$chosen_year, y = "%")
        
  sphere_cure <- geom_hline(yintercept = 75, 
                            colour = "darkgreen", 
                            linetype = 2, size = 0.25)
  
  sphere_default <- geom_hline(yintercept = 15, 
                               colour = "red", 
                               linetype = 2, size = 0.25)
    
  sphere_dead <- geom_hline(yintercept = 10, 
                            colour = "black", 
                            linetype = 2, size = 0.25)
  
  add_facets <- facet_wrap( ~ State, ncol = 6)

  if(input$standards) {
    z <- z + sphere_cure + sphere_default + sphere_dead + add_facets
  } else {
    z <- z + add_facets
  }

  z <- z + unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "state_performance")
```

### Locality

```{r}
xlocality <- reactive({
  monitoring %>% 
    calculate_performance() %>%
    filter(Year == input$chosen_year,
           State == input$state_name) %>%
    mutate(`Cure Rate` = cured_prop * 100,
           `Defaulter Rate` = defaulter_prop * 100,
           `Death Rate` = dead_prop * 100,
           `Non-response Rate` = nr_prop * 100,
           Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))
})

output$locality_performance <- renderPlotly({
  z <- xlocality() %>%
    ggplot(mapping = aes(x = Month, group = Locality)) +
    geom_line(mapping = aes(y = `Cure Rate`), colour = "darkgreen") +
    geom_line(mapping = aes(y = `Death Rate`), colour = "black") +
    geom_line(mapping = aes(y = `Defaulter Rate`), colour = "red") +
    geom_line(mapping = aes(y = `Non-response Rate`), colour = "gray70") +
    scale_y_continuous(limits = c(0, 100),
                       breaks = seq(from = 0, to = 100, by = 10)) +
    labs(title = paste(input$state_name, input$chosen_year, sep = " "),
         y = "%")    
    
  sphere_cure <- geom_hline(yintercept = 75, 
                            colour = "darkgreen", 
                            linetype = 2, size = 0.25)
  
  sphere_default <- geom_hline(yintercept = 15, 
                               colour = "red", 
                               linetype = 2, size = 0.25)
    
  sphere_dead <- geom_hline(yintercept = 10, 
                            colour = "black", 
                            linetype = 2, size = 0.25)
  
  add_facets <- facet_wrap( ~ Locality, nrow = 3)

  if(input$standards) {
    z <- z + sphere_cure + sphere_default + sphere_dead + add_facets
  } else {
    z <- z + add_facets
  }
  
  z <- z +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "locality_performance")
```

Row
--------------------------------------------------------------------------------

### State

```{r, fig.height = 5}
xstate_map <- reactive({
  xx <- aggregate(cbind(Cured, Death, Default, `Non-Responder`) ~ State + Month + Year, 
               data = monitoring, FUN = sum) %>% 
    calculate_performance() %>%
    filter(Year == input$chosen_year,
           Month == input$chosen_month) %>%
    mutate(`Cure Rate` = cured_prop * 100,
           `Defaulter Rate` = defaulter_prop * 100,
           `Death Rate` = dead_prop * 100,
           `Non-response Rate` = nr_prop * 100,
           Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))  
  
  state_map <- states
  state_map@data <- merge(state_map@data, xx, 
                          by.x = "State_En", 
                          by.y = "State")
  state_map
})

#output$sudanMap <- renderLeaflet({
#  leaflet() %>%
#    addTiles(urlTemplate = mapbox.terminal,
#             attribution = "Map by <a href='http://www.mapbox.com/'>Mapbox</a>")
#})

output$statePerformanceMap <- renderLeaflet({
  mapPalette <- brewer.pal(n = 5, name = "RdYlGn")
  pal <- colorNumeric(palette = mapPalette, 
                      domain = c(0, 100))
  tooltip <- paste("<strong>", xstate_map()@data$State, 
                   " State</strong><br/><strong>Cure Rate:</strong> ", 
                   round(xstate_map()@data$`Cure Rate`, digits = 2), "%<br/>",
                   input$chosen_month, " ", input$chosen_year, sep = "") %>%
    lapply(FUN = htmltools::HTML)
  
  leaflet() %>%
    addTiles(urlTemplate = mapbox.terminal,
             attribution = "Map by <a href='http://www.mapbox.com/'>Mapbox</a>") %>%
    addPolygons(data = xstate_map(),
                fillColor = pal(xstate_map()$`Cure Rate`),
                weight = 2,
                opacity = 1,
                color = pal(xstate_map()$`Cure Rate`),
                dashArray = "",
                fillOpacity = 0.8,
                highlight = highlightOptions(weight = 3,
                                             color = "#666",
                                             dashArray = "",
                                             fillOpacity = 0.7,
                                             bringToFront = TRUE),
                label = tooltip,
                labelOptions = labelOptions(style = list("font-weight" = "normal", 
                                                         padding = "3px 8px"),
                                            textsize = "12px",
                                            direction = "auto"),
                group = "Cure") %>%
        addPolygons(data = xstate_map(),
                    fillColor = pal(xstate_map()$`Defaulter Rate`),
                    weight = 2,
                    opacity = 1,
                    color = pal(xstate_map()$`Defaulter Rate`),
                    dashArray = "",
                    fillOpacity = 0.8,
                    highlight = highlightOptions(weight = 3,
                                                 color = "#666",
                                                 dashArray = "",
                                                 fillOpacity = 0.7,
                                                 bringToFront = TRUE),
                    label = tooltip,
                    labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                             padding = "3px 8px"),
                                                textsize = "12px",
                                                direction = "auto"),
                    group = "Defaulter") %>%
        addPolygons(data = xstate_map(),
                    fillColor = pal(xstate_map()$`Death Rate`),
                    weight = 2,
                    opacity = 1,
                    color = pal(xstate_map()$`Death Rate`),
                    dashArray = "",
                    fillOpacity = 0.8,
                    highlight = highlightOptions(weight = 3,
                                                 color = "#666",
                                                 dashArray = "",
                                                 fillOpacity = 0.7,
                                                 bringToFront = TRUE),
                    label = tooltip,
                    labelOptions = labelOptions(style = list("font-weight" = "normal", 
                                                             padding = "3px 8px"),
                                                textsize = "12px",
                                                direction = "auto"),
                    group = "Death") %>%
        addPolygons(data = xstate_map(),
                    fillColor = pal(xstate_map()$`Non-response Rate`),
                    weight = 2,
                    opacity = 1,
                    color = pal(xstate_map()$`Non-response Rate`),
                    dashArray = "",
                    fillOpacity = 0.8,
                    highlight = highlightOptions(weight = 3,
                                                 color = "#666",
                                                 dashArray = "",
                                                 fillOpacity = 0.7,
                                                 bringToFront = TRUE),
                    label = tooltip,
                    labelOptions = labelOptions(style = list("font-weight" = "normal", 
                                                             padding = "3px 8px"),
                                                textsize = "12px",
                                                direction = "auto"),
                    group = "Non-response") %>%
    addLegend(pal = pal, 
              values = c(0, 100),
              title = paste(input$chosen_month, input$chosen_year, sep = " "),
              opacity = 0.7,
              position = "bottomright", 
              labFormat = legend.format(digits = 1, between = " to ", suffix = "%"),
              layerId = "legend") %>%
	  addLayersControl(baseGroups = c("Cure", "Defaulter", 
	                                  "Death", "Non-response"),
	                   position = "topleft",
	                   options = layersControlOptions(collapsed = FALSE, 
	                                                  autoZIndex = TRUE))
})

leafletOutput(outputId = "statePerformanceMap")
```


### Locality


Responsiveness
================================================================================

Row
--------------------------------------------------------------------------------

### Seasonal Calendar

```{r}
output$calendar <- renderPlotly({
  seasonal_calendar %>%
    filter(year(start) == input$chosen_year) %>%
    vistime()
})

plotlyOutput(outputId = "calendar")
```


Row
--------------------------------------------------------------------------------

### Admissions at National Level

```{r}
admissions_defaulters <- reactive({
  aggregate(cbind(`New Admissions`, Default) ~ Month + Year, 
            data = monitoring, FUN = sum) %>% 
    filter(Year == input$chosen_year) %>%
    mutate(Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) %>%
    arrange(Month) %>%
    mutate(`Admissions (smoothed)` = smooth_m3a3(x = `New Admissions`),
           `Defaulters (smoothed)` = smooth_m3a3(x = Default))
})

output$admissions <- renderPlotly({
  z <- admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = Year)) +
    geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
    scale_y_continuous(limits = c(0, max(admissions_defaulters()[["New Admissions"]])),
                       breaks = seq(from = 0, 
                                    to = max(admissions_defaulters()[["New Admissions"]]),
                                    by = 5000)) +
    labs(title = input$chosen_year) +
    unicef_theme
  
  if(input$smooth) {
    z <- admissions_defaulters() %>%
      ggplot(mapping = aes(x = Month, group = Year)) +
      geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
      geom_line(mapping = aes(y = `Admissions (smoothed)`), colour = "gray90") +
      scale_y_continuous(limits = c(0, max(admissions_defaulters()[["New Admissions"]])),
                         breaks = seq(from = 0, 
                                      to = max(admissions_defaulters()[["New Admissions"]]),
                                      by = 5000)) +
      labs(title = input$chosen_year) +
      unicef_theme
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "admissions")
```

Row
--------------------------------------------------------------------------------

### Defaulters at National Level

```{r}
output$defaulters <- renderPlotly({
  z <- admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = Year)) +
    geom_line(mapping = aes(y = `Default`), colour = "red") +
    scale_y_continuous(limits = c(0, max(admissions_defaulters()[["Default"]])),
                       breaks = seq(from = 0, 
                                    to = max(admissions_defaulters()[["Default"]]),
                                    by = 500)) +
    labs(title = input$chosen_year) +
    unicef_theme
  
  if(input$smooth) {
    z <- admissions_defaulters() %>%
      ggplot(mapping = aes(x = Month, group = Year)) +
      geom_line(mapping = aes(y = `Default`), colour = "red") +
      geom_line(mapping = aes(y = `Defaulters (smoothed)`), colour = "gray90") +
      scale_y_continuous(limits = c(0, max(admissions_defaulters()[["Default"]])),
                         breaks = seq(from = 0, 
                                      to = max(admissions_defaulters()[["Default"]]),
                                      by = 500)) +
      labs(title = input$chosen_year) +
      unicef_theme    
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "defaulters")
```

Row
--------------------------------------------------------------------------------

### Admissions at State Level

```{r, fig.height = 8}
state_admissions_defaulters <- reactive({
  aggregate(cbind(`New Admissions`, Default) ~ State + Month + Year, 
            data = monitoring, FUN = sum) %>% 
    filter(Year == input$chosen_year) %>%
    mutate(Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) %>%
    group_by(State) %>%
    arrange(Month, .by_group = TRUE) %>%
    mutate(`Admissions (smoothed)` = smooth_m3a3(x = `New Admissions`),
           `Defaulters (smoothed)` = smooth_m3a3(x = Default))
})

output$state_admissions <- renderPlotly({
  z <- state_admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
    scale_y_continuous(limits = c(0, max(state_admissions_defaulters()[["New Admissions"]])),
                       breaks = seq(from = 0, 
                                    to = max(state_admissions_defaulters()[["New Admissions"]]),
                                    by = 1000)) +    
    labs(title = input$chosen_year) +
    facet_wrap( ~ State, ncol = 6) +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))  
  
  if(input$smooth) {
      z <- state_admissions_defaulters() %>%
        ggplot(mapping = aes(x = Month, group = State)) +
        geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
        geom_line(mapping = aes(y = `Admissions (smoothed)`), colour = "gray90") +
        scale_y_continuous(limits = c(0, max(state_admissions_defaulters()[["New Admissions"]])),
                           breaks = seq(from = 0, 
                                        to = max(state_admissions_defaulters()[["New Admissions"]]),
                                        by = 1000)) +    
        labs(title = input$chosen_year) +
        facet_wrap( ~ State, ncol = 6) +
        unicef_theme +
        theme(axis.text.x = element_text(size = 8, angle = 90),
              axis.text.y = element_text(size = 8))
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "state_admissions")
```

Row
--------------------------------------------------------------------------------

### Defaulters at State Level

```{r, fig.height = 8}
output$state_defaulters <- renderPlotly({
  z <- state_admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = Default), colour = "red") +
    scale_y_continuous(limits = c(0, max(state_admissions_defaulters()[["Default"]])),
                       breaks = seq(from = 0, 
                                    to = max(state_admissions_defaulters()[["Default"]]),
                                    by = 100)) +    
    labs(title = input$chosen_year) +
    facet_wrap( ~ State, ncol = 6) +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))  
  
  if(input$smooth) {
    z <- state_admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = Default), colour = "red") +
    geom_line(mapping = aes(y = `Defaulters (smoothed)`), colour = "gray90") +  
    scale_y_continuous(limits = c(0, max(state_admissions_defaulters()[["Default"]])),
                       breaks = seq(from = 0, 
                                    to = max(state_admissions_defaulters()[["Default"]]),
                                    by = 100)) +    
    labs(title = input$chosen_year) +
    facet_wrap( ~ State, ncol = 6) +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))  
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "state_defaulters")
```

Row
--------------------------------------------------------------------------------

### Admissions at Locality Level

```{r, fig.height = 8}
locality_admissions_defaulters <- reactive({
  monitoring %>% 
    filter(Year == input$chosen_year,
           State == input$state_name) %>%
    mutate(Month = factor(x = Month, 
                          levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) %>%
    group_by(Locality) %>%
    arrange(Month, .by_group = TRUE) %>%
    mutate(`Admissions (smoothed)` = smooth_m3a3(x = `New Admissions`),
           `Defaulters (smoothed)` = smooth_m3a3(x = Default))
})

output$locality_admissions <- renderPlotly({
  z <- locality_admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
    labs(title = paste(input$state_name, input$chosen_year, sep = " ")) +
    facet_wrap( ~ Locality, nrow = 3) +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))  
  
  if(input$smooth) {
      z <- locality_admissions_defaulters() %>%
        ggplot(mapping = aes(x = Month, group = Locality)) +
        geom_line(mapping = aes(y = `New Admissions`), colour = "blue") +
        geom_line(mapping = aes(y = `Admissions (smoothed)`), colour = "gray90") +
        labs(title = paste(input$state_name, input$chosen_year, sep = " ")) +
        facet_wrap( ~ Locality, nrow = 3) +
        unicef_theme +
        theme(axis.text.x = element_text(size = 8, angle = 90),
              axis.text.y = element_text(size = 8))
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "locality_admissions")
```

Row
--------------------------------------------------------------------------------

### Defaulters at Locality Level

```{r, fig.height = 8}
output$locality_defaulters <- renderPlotly({
  z <- locality_admissions_defaulters() %>%
    ggplot(mapping = aes(x = Month, group = State)) +
    geom_line(mapping = aes(y = Default), colour = "red") +
    labs(title = paste(input$state_name, input$chosen_year, sep = " ")) +
    facet_wrap( ~ Locality, nrow = 3) +
    unicef_theme +
    theme(axis.text.x = element_text(size = 8, angle = 90),
          axis.text.y = element_text(size = 8))  
  
  if(input$smooth) {
      z <- locality_admissions_defaulters() %>%
        ggplot(mapping = aes(x = Month, group = Locality)) +
        geom_line(mapping = aes(y = `Default`), colour = "red") +
        geom_line(mapping = aes(y = `Defaulters (smoothed)`), colour = "gray90") +
        labs(title = paste(input$state_name, input$chosen_year, sep = " ")) +
        facet_wrap( ~ Locality, nrow = 3) +
        unicef_theme +
        theme(axis.text.x = element_text(size = 8, angle = 90),
              axis.text.y = element_text(size = 8))
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "locality_defaulters")
```

Case-finding
================================================================================

